# Name: Jennah Yasin
# Date: March 28, 2022
# Title: Lab 4 - Makefile
# Description: Makefile for fifo.c in Lab 4

fifo: fifo.o
	gcc -o fifo queue.c node.c fifo.c
fifo.o: fifo.c
	gcc -c -o fifo.o fifo.c
