# Name: Jennah Yasin
# Date: March 22, 2022
# Title: Lab 2 - Steps 1 - 3
# Description: Makefile for steps 1 - 3

#For Lab3 Step 1:
Lab3_Step1: Lab3_Step1.o
	gcc -o Lab3_Step1 Lab3_Step1.o

Lab3_Step1.o: Lab3_Step1.c
	gcc -c -o Lab3_Step1.o Lab3_Step1.c

#For Lab3 Step2:
Lab3_Step2: Lab3_Step2.o
	gcc -o Lab3_Step2 Lab3_Step2.o

Lab3_Step2.o: Lab3_Step2.c
	gcc -c -o Lab3_Step2.o Lab3_Step2.c
#For Lab3 Step3:
Lab3_Step3: Lab3_Step3.o
	gcc -o Lab3_Step3 Lab3_Step3.o

Lab3_Step3.o: Lab3_Step3.c
	gcc -c -o Lab3_Step3.o Lab3_Step3.c