# Name: Jennah Yasin
# Date: March 15, 2022
# Title: Lab 2 - Steps 1 & 5
# Description: Makefile for steps 1 & 5
Lab2_Step1: Lab2_Step1.o
	gcc -o Lab2_step1 Lab2_Step1.o

Lab2_Step1.o: lab2_step1.c
	gcc -c -o Lab2_Step1.o lab2_step1.c

Lab2_Step5: Lab2_Step5.o
	gcc -o Lab2_Step5 Lab2_Step5.o

Lab2_Step5.o: lab2_step5.c
	gcc -c -o Lab2_Step5.o lab2_step5.c

